project:
  type: website
  output-dir: docs

website:
  title: "Vikrant"
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/vikrant-mehta/
      - icon: github
        href: https://github.com/vikrantmehta123
      - icon: code
        href: https://leetcode.com/u/vikrantmehta123/
      - text: "{{<fa chess-queen>}}"
        href: https://lichess.org/@/vikrant-123
    left:
      - href: about.qmd
        text: About
      - href: index.qmd
        text: Blog
      - text: Projects
        href: projects.qmd 
      - text: DSA
        href: dsa/index.qmd
        
  sidebar:
      - id: dsanotes
        style: docked
        search: true
        contents: dsa
        sort: order

format:
  html:
    theme: 
      light: flatly
      dark: darkly 
    css: styles.css
    toc: true
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Sofia&family=WindSong:wght@400;500&display=swap" rel="stylesheet">


