---
title: "From Ashes to an Empire!"
author: "Vikrant Mehta"
date: "2020-05-07"
categories: [Business, People]
description: ""
---

We went to Sinnar to meet a man about whom I knew virtually nothing. But very soon I realised what the name *Amol Kasar* meant. A man in his mid-thirties, Amol Kasar was a brand in himself, an owner of grand furniture stores chain in Sinnar.  

> "I was 17, I’d failed my 10th grade, and I was barely keeping in college when I thought about starting my own furniture business." He said.

Though Amol didn’t have a typical schooling background, he had what is needed to be successful—he had the courage to try.

> "My father told me, 'Look, I don’t have any money to give you. I can only give you the space you need to start your business.'"

> "I agreed. I took out a loan of 50,000 Rs in 1998 to buy the furniture and arranged for a grand opening ceremony at a five-star hotel."

The lunch at a five-star hotel, by a 17-year-old, was surely going to be the talk of the town.

> "The ceremony was supposed to take place the next day, and I had nothing to show for as my business. At that time, Ulhasnagar was *the* furniture market. I travelled to Ulhasnagar the day before the opening. I enquired from many traders but I was 17! They took me for a prankster and shook me off. Later in the day, I started showing the cash in my pocket to make them believe that I meant business. I bought the furniture at whatever price they asked; I didn’t even know what bargaining meant. Even after that, there was the problem of transporting the furniture back to Sinnar. The porters, too, took me for a prankster and refused to load the goods in my truck. I paid them more than they asked for and loaded the cargo alongside them. At last, I started my return journey."

But the God’s test wasn’t over yet.

> "It was raining and it was midnight. The driver didn’t see a large pit on the road, and we crashed. We were stuck. We had a truck full of furniture, we were soaked wet, and in the middle of nowhere at two in the morning. After a long while of walking around and waking a few people, we finally managed to get our truck on track. I reached Sinnar an hour before the opening. Phew! But there were preparations left—I hadn’t even painted my store’s name. I scrambled off again to find a painter. Alas, there it was! My first—'Amol Furnitures.'"

But the drama doesn’t end here. The opening ceremony went as planned but it rained, and rained, and rained after that. Not a single customer came. He had to wait a long while to earn his first income.

> "The next evening, there came a teacher from a local school. She wanted to buy a cupboard. But wait a second! We didn’t have electricity! I sold my first piece of furniture with a candle in my hand. I’d earned my first. It was 5,100 Rs."

At 17, he knew he was supposed to do business. Business runs in Amol’s blood.

> "My father had three brothers. All of them inherited something from their father, but dad got nothing. He started a kitchenware business on his own, in which me and my elder brother helped. In those days, steel kitchen racks needed custom fitting. We took great joy in earning this 'fitting' money."

After the first income of 5,100 Rs, slowly he paid off the 50,000 loan, only to take another loan. This time, of 1 lakh Rs. With that money, he expanded his business. Then again, he paid off that loan and took another loan of 2.5 lakhs. He paid off that loan and took out yet another loan of 5 lakhs to expand. He now owned a couple of furniture stores.

But when he started, Sinnar was already home to multiple well-established furniture businesses. Wasn’t he threatened by the competition?

> "I was an inexperienced lad compared to the well-established traders. These traders even tried to put me out of competition. But somehow I managed to hold on. Maybe the customers put more trust in me than the others because I was young and inexperienced. I too, was very honest and straightforward in all my business, and we’ve never compromised quality, which is why we’ve still maintained that trust."

Slowly, as the name Amol Furniture spread, the competition went out of competition. But the ups of business don’t come without the downs.

> "2nd July, 2018. I got a call early in the morning. I picked it up immediately. I knew something was up. One of my furniture stores had been lit on fire. By the time I’d reached the store, there was nothing left, just flames and ashes. I saw my whole 10,000 sq.ft. showroom burn in front of my eyes. We still don’t know who did it, but it cost me about 70-80 lakhs. That morning I realised, one night is good enough for success to burn down to ashes."

> "I had only two choices that day: I could cry or I could rebuild. I chose to rebuild. On that very day, we had to complete a wedding order. 11 am was the wedding muhurta. I called my suppliers in Pune at 6 in the morning, and arranged for that order. It arrived at the scene on time."

Amol Kasar is a man who holds the capacity to turn a rock into gold.

> "Within days, I rented another dusty property to start a showroom. On the 45th day, we reopened. I offered to repay all the money I owed to my suppliers, regardless of the loss. They too, didn’t take the money, instead offered me a helping hand. My family and friends were a great support through this time. We fought and we’ve bounced back."

Not only did he bounce back, he’s aiming for more stars in the future. Amol Furnitures is far from done yet. The sense of responsibility keeps the man going.

> "The next goal is to unite my five showrooms into one big furniture mall. In a couple of years, we’re expecting to finish the 1 lakh square ft construction."

But over the course of years, he’s learned his lessons.

> "You need to make investments, but you also need to make the investments secure. Or else, your success gets burned to ashes overnight."

Before we finished our interview, I couldn’t help but ask him, "Did you *ever* finish your college degree?"

> "I didn’t." He chuckles. "I had everything I could ask for—a family, friends, a career. I didn’t need a college degree."

Amol Kasar has built his empire from scratch—an empire built upon honesty and uncompromising quality.

An empire built with courage and confidence in one’s abilities.

## Advice to the Youth:

> "Make decisions. I’ve seen a lot of people who keep asking for advice but never make their own decision. Others have your best interests at heart but they don’t know your story; they only know their own story. They give advice according to their story, which may or may not be useful to you. Don’t rely too much on advice. Make your own decisions, and make them quickly. Even if the decision is wrong, you’ll get to learn something. But make a decision."

> "There are certain things in life that are more important than thrill. These things need to be done first. The youth, nowadays, prioritises enjoyment over these things. Do what is best for your life first, then enjoy life."

> "Success needs to be balanced. It needs to be in all areas of life like personal, financial, social. You cannot be successful if you’re a success in one area of life but a failure in another. You have to be successful in all areas even if it means less success in one area."

---