---
page-layout: full
title: "Leet Coding Using Python"
sidebar: true
toc: false
page-navigation: true
title-block-banner: true
author: "Vikrant Mehta"
date: "2024-11-10"
---

Welcome to the supplementary GitHub repository for the course **Programming, Data Structures, and Algorithms Using Python (BSCS2002)** which is offered as part of the **IITM BS in Data Science and Applications** program. You can find more information about the course [here](https://study.iitm.ac.in/ds/course_pages/BSCS2002.html). There is also an [online textbook](https://pdsaiitm.github.io/) that you can use as reference throughout the course.

I created this repository as a part of my work as a Teaching Assistant for this course. In this repository, you will find a solution explanations and code implementations for a list curated Leet Code problems that span the topics covered in the lectures. The problems are categorized such that they correspond to each week's course content. 

## 📝 Overview of Course Topics:
- **Week 1**: Overview and recap of Python
- [**Week 2**](https://vikrantmehta123.github.io/dsa/sorting-and-searching/): Sorting and Searching Algorithms- Binary Search, Quick Sort, Merge Sort, Insertion Sort, Selection Sort.
- [**Week 3**](https://vikrantmehta123.github.io/dsa/linked-lists-stacks-and-queues/): Stacks, Heaps, Linked Lists, Arrays, and Hashing
- [**Week 4**](https://vikrantmehta123.github.io/dsa/graphs/): Graph Algorithms- BFS, DFS, Topological Sorting, DAG
- [**Week 5**](https://vikrantmehta123.github.io/dsa/shortest-paths-and-mcst/): Graph Algorithms- Shortest Paths, Minimum Cost Spanning Trees
- [**Week 6**](https://vikrantmehta123.github.io/dsa/heaps-and-trees/): Union Find, Priority Queues, Heaps, Binary Search Trees
- [**Week 7**](https://vikrantmehta123.github.io/dsa/greedy/): Balanced Search Trees, Greedy Algorithms- Huffman Coding, Interval Scheduling
- [**Week 8**](https://vikrantmehta123.github.io/dsa/divide-and-conquer/): Divide and Conquer- Quick Select, Closest Pair of Points, Counting Inversions
- [**Week 9**](https://vikrantmehta123.github.io/dsa/dynamic-programming/): Dynamic Programming- Grid Paths, Edit Distance, Longest Common Subsequence
- [**Week 10**](https://vikrantmehta123.github.io/dsa/string-matching/): String Matching- Boyer-Moore, Rabin-Karp, KMP, Tries, Regular Expressions
- **Week 11**: Network Flows, Linear Programming, NP Hardness
- **Week 12**: Summary

## 🔎 About the Problems

The problems selected from LeetCode cover the range of difficulties, from easy to hard. Each problem is chosen to reinforce the concepts learned during the week, and provides both practice and an understanding of the topics. You are encouraged to attempt the problems before looking at the solution approach and code.

## 🙌 Credits

This repository is a collaborative effort between the course instructors, teaching assistants, and the enthusiastic community of students. Special thanks to Professor Madhavan Mukund Sir, the instructors Atul Pratap Singh Sir, S Satyanarayana Sir for their continued support, and a shoutout to the creators of the LeetCode platform for providing a wealth of coding challenges. 

Happy coding! 🚀

---