---
title: "Money Map"
author: "Vikrant Mehta"
date: "2024-10-18"
categories: [Software Engineering]
description: "Money Map is a financial tool that lets you run simulations with different inputs and get an approximation of your financial plans."
---

### Project Overview

Financial planning is of great importance, especially if you're young and starting out in your career. As a part of the CFA curriculum, I created simulations for my personal financial planning. These simulations, I figured, were important to keep in the back of the mind as we went about our lives. They give us a sense of what decisions should we take and what decisions should we avoid. Not only that, but they make us think about budgeting and expenditures. 

Money Map does exactly that. It lets you run simulations that you can use for your financial planning. It also includes additional resources that you can explore as you go about planning your finances. You can access the project live [here](https://vikrantmehta123.github.io/money-map/).

### Features

- Simulator based on different input parameters
- Plots of the simulation
- Resources for further study

### Tech Stack

- ReactJS
- Plotly

**GitHub Repository**  
For more details, the full source code can be found on GitHub: [Source Code](https://github.com/vikrantmehta123/money-map)